AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation template for creating IAM role and OIDC provider for Github Actions to assume to execute cost tracking and limited cloudformation operations
Resources:
  GithubIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: IcsiItGithubOidcRoleForCostTracking
      Description: Role for Github Actions to assume to execute limited cost tracking and cloudformation operations
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref OIDCProvider
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: repo:icsi-it/AWS-cost-tracking:*
      Policies:
        - PolicyName: GithubActionsCloudformationAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStack*
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:CancelUpdateStack
                  - cloudformation:RollbackStack
                  - cloudformation:DescribeChangeSet*
                  - cloudformation:CreateChangeSet
                  - cloudformation:DeleteChangeSet
                  - cloudformation:ExecuteChangeSet
                Resource: !Sub arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/IcsiItCostTracking/*
              - Effect: Allow
                Action:
                  - sts:GetCallerIdentity
                Resource: '*'
        - PolicyName: GithubActionsCostTrackingAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:*
                Resource: !Sub arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:IcsiItCostTracking*
              - Effect: Allow
                Action:
                  - iam:GetRole*
                  - iam:CreateRole*
                  - iam:PutRole*
                  - iam:DeleteRole*
                  - iam:List*
                  - iam:AttachRole*
                  - iam:DetachRole*
                  - iam:PassRole*
                Resource: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/IcsiItCostTracking*
              - Effect: Allow
                Action:
                  - iam:GetPolicy*
                  - iam:CreatePolicy*
                  - iam:PutPolicy*
                  - iam:DeletePolicy*
                  - iam:List*
                Resource: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/IcsiItCostTracking*
              - Effect: Allow
                Action:
                  - aws-portal:ViewBilling
                Resource: '*'
              - Effect: Allow
                Action:
                  - lambda:Add*
                  - lambda:Create*
                  - lambda:Get*
                  - lambda:Delete*
                  - lambda:Remove*
                  - lambda:Update*
                Resource:
                  - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:IcsiItCostTracking*
                  - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPython*
              - Effect: Allow
                Action:
                  - secretsmanager:Create*
                  - secretsmanager:Put*
                  - secretsmanager:Update*
                  - secretsmanager:Delete*
                  - secretsmanager:Restore*
                Resource:
                  - !Sub arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/IcsiItCostTracking/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:DeleteLogGroup
                  - logs:PutRetentionPolicy
                Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/IcsiItCostTracking*
              # Discussed allowing this level of access for budgets and cost estimation w/Graham Freeman - Agreed it's an acceptable level of access for now.
              # Could revisit to allow more granular access.
              - Effect: Allow
                Action:
                  - budgets:DescribeBudgetActionsForAccount
                  - budgets:DescribeBudgetAction
                  - budgets:ViewBudget
                  - budgets:DescribeBudgetActionHistories
                  - budgets:DescribeBudgetActionsForBudget
                  - budgets:CreateBudgetAction
                  - budgets:ModifyBudget
                  - budgets:UpdateBudgetAction
                  - budgets:ExecuteBudgetAction
                  - budgets:DeleteBudgetAction
                Resource: '*'
              - Effect: Allow
                Action:
                  - ce:DescribeReport
                  - ce:CreateReport
                  - ce:UpdateReport
                  - ce:DeleteReport
                  - ce:CreateAnomalyMonitor
                  - ce:GetAnomalyMonitors
                  - ce:UpdateAnomalyMonitor
                  - ce:DeleteAnomalyMonitor
                  - ce:CreateAnomalySubscription
                  - ce:GetAnomalySubscriptions
                  - ce:UpdateAnomalySubscription
                  - ce:DeleteAnomalySubscription
                  - ce:GetAnomalies
                Resource: '*'
  OIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      # The repeating f's are deliberate and not a placeholder/mistake. See:
      # https://github.com/aws-actions/configure-aws-credentials?tab=readme-ov-file#configuring-iam-to-trust-github
      # and: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc_verify-thumbprint.html
      ThumbprintList:
        - ffffffffffffffffffffffffffffffffffffffff